site_name: SeamLess
repo_url: https://github.com/anwaldt/seamless

theme:
    name: material
    highlightjs: true
    logo: graphics/interface_HVC_small.png

plugins:
#    - with-pdf
#    - search
#    - mkpdfs

# bibtex:
#      bib_file: "refs.bib"
#      cite_style: "pandoc"
extra:
    generator: false

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
#docs:
#    ../graphics/
#      hufo_flow_1.png

nav:
#    - Back to Project Page: https://hvc.berlin/projects/hufo-listening-room/
    - About the System: about.md
    - Using the System: reaper.md
    - SeamLess Plugins:
      - Plugins: plugins.md
      - OSC Paths: paths.md
    - Technical Documentation:
      - Signal Flow: signalflow.md
      - SuperCollider: supercollider.md
      - WFS/WONDER: wonder.md
      - Reverb: reverb.md
      - OSC Router: oscrouter.md
      - System Setup: system_setup.md
