- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 9
  minute: 0
  second: 0
  video_index: 0
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 9
  minute: 3
  second: 20
  video_index: 1
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 9
  minute: 19
  second: 40
  video_index: 2
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 9
  minute: 39
  second: 5
  video_index: 0
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 9
  minute: 42
  second: 20
  video_index: 4
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 10
  minute: 0
  second: 0
  video_index: 5
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 10
  minute: 3
  second: 20
  video_index: 6
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 10
  minute: 19
  second: 40
  video_index: 7
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 10
  minute: 39
  second: 5
  video_index: 5
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 10
  minute: 42
  second: 20
  video_index: 9
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 0
  second: 0
  video_index: 10
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 3
  second: 20
  video_index: 11
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 19
  second: 40
  video_index: 12
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 39
  second: 5
  video_index: 10
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 42
  second: 20
  video_index: 14
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 0
  second: 0
  video_index: 15
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 3
  second: 20
  video_index: 16
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 19
  second: 40
  video_index: 17
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 39
  second: 5
  video_index: 15
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 42
  second: 20
  video_index: 19
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 0
  second: 0
  video_index: 20
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 3
  second: 20
  video_index: 21
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 19
  second: 40
  video_index: 22
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 39
  second: 5
  video_index: 20
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 42
  second: 20
  video_index: 24
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 0
  second: 0
  video_index: 25
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 3
  second: 20
  video_index: 26
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 19
  second: 40
  video_index: 27
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 39
  second: 5
  video_index: 25
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 42
  second: 20
  video_index: 29
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 0
  second: 0
  video_index: 30
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 3
  second: 20
  video_index: 31
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 19
  second: 40
  video_index: 32
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 39
  second: 5
  video_index: 30
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 42
  second: 20
  video_index: 34
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 0
  second: 0
  video_index: 35
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 3
  second: 20
  video_index: 36
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 19
  second: 40
  video_index: 37
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 39
  second: 5
  video_index: 35
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 42
  second: 20
  video_index: 39
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 0
  second: 0
  video_index: 40
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 3
  second: 20
  video_index: 41
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 19
  second: 40
  video_index: 42
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 39
  second: 5
  video_index: 40
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 42
  second: 20
  video_index: 44
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 0
  second: 0
  video_index: 45
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 3
  second: 20
  video_index: 46
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 19
  second: 40
  video_index: 47
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 39
  second: 5
  video_index: 45
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 42
  second: 20
  video_index: 49
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 19
  minute: 0
  second: 0
  video_index: 50
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 19
  minute: 3
  second: 20
  video_index: 51
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 19
  minute: 19
  second: 40
  video_index: 52
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 19
  minute: 39
  second: 5
  video_index: 50
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 19
  minute: 42
  second: 20
  video_index: 54
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 20
  minute: 0
  second: 0
  video_index: 55
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 20
  minute: 3
  second: 20
  video_index: 56
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 20
  minute: 19
  second: 40
  video_index: 57
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 20
  minute: 39
  second: 5
  video_index: 55
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 20
  minute: 42
  second: 20
  video_index: 59
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 21
  minute: 0
  second: 0
  video_index: 60
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 21
  minute: 3
  second: 20
  video_index: 61
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 21
  minute: 19
  second: 40
  video_index: 62
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 21
  minute: 39
  second: 5
  video_index: 60
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 21
  minute: 42
  second: 20
  video_index: 64
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 22
  minute: 0
  second: 0
  video_index: 65
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 22
  minute: 3
  second: 20
  video_index: 66
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 22
  minute: 19
  second: 40
  video_index: 67
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 22
  minute: 39
  second: 5
  video_index: 65
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 22
  minute: 42
  second: 20
  video_index: 69
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 23
  minute: 0
  second: 0
  video_index: 70
- audio_index: 2
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 23
  minute: 3
  second: 20
  video_index: 71
- audio_index: 3
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 23
  minute: 19
  second: 40
  video_index: 72
- audio_index: 1
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 23
  minute: 39
  second: 5
  video_index: 70
- audio_index: 4
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 23
  minute: 42
  second: 20
  video_index: 74
